### ISSUE TITLE
"Error: Cannot find module 'winston'" when running ./start.sh after switching to testing branch

### ISSUE THREAD

**Issue by HughMcDonnell** [filipay/monitroom#4]
## Info

New error after switching to testing branch:

> \> monitroom@0.0.0 start /home/hugh/Development/workspace/monitroom
> \> node ./bin/www
> 
> module.js:457
>     throw err;
>     ^
> 
> Error: Cannot find module 'winston'
>     at Function.Module._resolveFilename (module.js:455:15)
>     at Function.Module._load (module.js:403:25)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/hugh/Development/workspace/monitroom/storage/logger.js:1:77)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
> 
> npm ERR! Linux 4.4.0-34-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v6.4.0
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! monitroom@0.0.0 start: `node ./bin/www`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the monitroom@0.0.0 start script 'node ./bin/www'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the monitroom package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./bin/www
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs monitroom
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls monitroom
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/hugh/Development/workspace/monitroom/npm-debug.log

## Solution

?

**Comment by filipay** [comment]
This happens because a new dependency was added to 'testing'.  'master' hasn't received the update yet.

Run `npm install` again to get the 'winston' dependency.
